### ISSUE TITLE
Artifact of binary target has changed checksum

### ISSUE THREAD

**Issue by rzulkoski** [thegrizzlylabs/geniusscan-sdk-spm#2]
When building on my CI server I am sometimes getting a failure with this message:

![image](https://user-images.githubusercontent.com/3171325/148784726-63cab89a-b296-4ee8-9e76-b0bca8a62cd6.png)

Has anyone else ran into this? I can get it to go away for a little while by removing `~/Library/Caches/org.swift.swiftpm`. I'm currently using Xcode 13.0 and can't switch to 13.2.1 until I'm able to deprecate iOS 12 in February.

Is there any chance that you are modifying a tagged release after the fact? I'm not sure how else to explain the message I'm receiving.

Thanks!

**Comment by bvirlet** [comment]
Hello @rzulkoski,

Thanks for your question. No, we are not modifying tagged release after the fact. 

We have also seen this on our internal CI as well, for the Genius Scan SDK that we dogfood in Genius Scan, and for other Swift packages with binary artifacts. We suspect this is due to an incomplete download of the binary artifacts in the cache, resulting in this problem the next time xcodebuild attempts to re-download the artifacts.

SPM was so finicky at downloading binary artifacts that we even added a workaround on our CI to automatically clear the DerivedData if we detected such an error in the logs. Maybe that would help a bit here. Hopefully future versions of Xcode/SPM get more stable.

**Comment by rzulkoski** [comment]
I appreciate the quick response and thank you for sharing your experience with binary artifacts. I will keep my fingers crossed as well for more stability around SPM in future Xcode releases. 🤞
